package server

const( 	
		RANGO_I_TRES = 4
		RANGO_F_TRES = 7
		RANGO_I_DOS = 8
		RANGO_F_DOS = 11
		RANGO_I_UNO = 12
		RANGO_F_UNO = 13
		RANGO_I_DOCE = 14
		RANGO_F_DOCE = 17
		RANGO_I_ONCE = 18
		RANGO_F_ONCE = 21
		RANGO_I_DIEZ = 22
		RANGO_F_DIEZ = 25
		RANGO_I_SIETE = 26
		RANGO_F_SIETE = 27
		RANGO_I_SEIS = 28
		RANGO_F_SEIS = 31
		RANGO_I_CINCO = 32
		RANGO_F_CINCO = 35
		RANGO_I_CUATRO = 36
		RANGO_F_CUATRO = 39
)